### ISSUE TITLE
viewBox attribute needs to be whitelisted for SVG

### ISSUE THREAD

**Issue by BigAB** [canjs/can-view-parser#22]
![image](https://cloud.githubusercontent.com/assets/76821/20281370/dc9291a6-aa75-11e6-84b2-b6af9bbbce44.png)

`viewBox` is a valid and common attribute needed for SVGs.
https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox

`can-view-parser` converts it to `view-box`, which then breaks svg sizing.

**Comment by BigAB** [comment]
<img width="567" alt="screen shot 2016-11-24 at 11 50 57 pm" src="https://cloud.githubusercontent.com/assets/76821/20615573/e9c31d7c-b2a0-11e6-9c00-f5713f1cf782.png">

Just showing why I want this fixed, it really muddles up the console/terminal/log

**Comment by marshallswain** [comment]
It's producing this warning because of the SVG file used in the GitHub login button in Bitcentive.  It doesn't ruin the rendering, but the warning might be fixed by #24.

**Comment by chasenlehara** [comment]
I believe this is still an issue because I’m seeing it in this project: https://github.com/stealjs/steal-canjs-example

The fix made a change to `caseMatters` on this line: https://github.com/canjs/can-view-parser/blob/master/can-view-parser.js#L40

However, that only seems to be used for element/tag names, not attribute names (which `viewBox` is), so I think this bug is still there.
