### ISSUE TITLE
Quoted arguments in stache helpers can cause parse errors within attributes ~8

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-view-parser#4]
From https://github.com/canjs/canjs/issues/1536

```
can.stache('<span title="{{#if "test"}}abc{{/if}}"></span>')()
```

**Comment by phillipskevin** [comment]
This is working fine in 3.0: http://jsbin.com/yuhahewadi/1/edit?html,js,output

Using `can.stache.from` doesn't work: http://jsbin.com/qabafocila/1/edit?html,js,output

This throws the error:
```
Error: Failed to execute 'setAttribute' on 'Element': 'title="{{#if " test"}}abc{{="" if}}"' is not a valid attribute name.
    at Error (native)
    at Object.setAttribute (https://rawgit.com/canjs/canjs/v3.0.0-pre.6/dist/global/can.all.js:3994:40)
    at processNode (https://rawgit.com/canjs/canjs/v3.0.0-pre.6/dist/global/can.all.js:5676:37)
    at processNodes (https://rawgit.com/canjs/canjs/v3.0.0-pre.6/dist/global/can.all.js:5605:34)
```

This is because the template in the DOM is 
```
<span title="{{#if " test"}}abc{{="" if}}"="">span</span>
```

I'm not sure if there's anything that can be done about that.

I also tried loading the template with `steal-stache` and that also works fine.

@justinbmeyer I have a test that shows this is working in can-view-parser. Should I add that? Or just close this issue? Or is there something else you think should be fixed here?

**Comment by justinbmeyer** [comment]
Does it work if you use a `<script>` tag?  http://jsbin.com/lunona/1/edit?html,js,output  Seems like it.  Yeah, just close it.

**Comment by justinbmeyer** [comment]
Does it break in 2.3?

**Comment by phillipskevin** [comment]
Yeah, the reason my earlier example using `can.stache.from` didn't work was just that I wrote it wrong, but like you said, it works fine with a `<script>` tag. 

This is working fine in 2.3 also. In 2.2.9 it breaks with

```
error Error: Parse Error: <span title="{{#if "test"}}abc{{/if}}">span</span>
  
    at HTMLParser (http://canjs.com/release/2.2.9/can.jquery.js:4084:23)
    at stache (http://canjs.com/release/2.2.9/can.stache.js:608:9)
    at Object.fragRenderer (http://canjs.com/release/2.2.9/can.stache.js:780:20)
```

Closing the issue.
